### ISSUE TITLE
delete photo on camera

### ISSUE THREAD

**Issue by peterbaricic** [TypedProject/ts-gphoto2-driver#11]
Hi,
is there any way how to delete photo on camera or capture photo without saving the photo on camera?

Thanks

**Comment by goooseman** [comment]
Hi,

`CameraFile` class has a `getDataAndSizeAsync` instance method, which returns the photo object as binary (`Buffer` object) or base64 (string).

You can use it like this:

```
const camera = new Camera();
camera.initialize();
const cameraFile = camera.captureImage();
const photo = await cameraFile.getDataAndSizeAsync('binary' | 'base64')
```

**Comment by goooseman** [comment]
If that is what you were looking for, please close the issue.

**Comment by peterbaricic** [comment]
Thanks for help,
but the captured photo is still on the camera, which is what I don't want.
So there is no way to delete captured photo on camera after copying to computer? Or just have it captured directly to computer?

**Comment by goooseman** [comment]
This library is just a wrapper around [gphoto2 C library](http://www.gphoto.org/doc/api/).

As far as I know, it do not support an option to save the file to the camera's SD card or not. For some cameras it is saving, for some - not.

It has a delete command `gp_filesystem_delete_file`, but it is not implemented in this wrapper.

So you can implement a bridge between libgphoto2 and this wrapper to use it. PR's are always welcome 😀

By the way, on my Canon 80D I can capture images even without any SD card. That is how I'm using it and do not worry about filesystem size, maybe it can be suitable for your usecase too.

**Comment by peterbaricic** [comment]
ok, thanks for the info anyway and thanks again for this library/wrapper
