### ISSUE TITLE
Triggering bulb mode explicitly, is it possible to then download the file?

### ISSUE THREAD

**Issue by Mike-Dax** [TypedProject/ts-gphoto2-driver#12]
Hi there,

I've got a Canon 5D3 that I'm trying to trigger bulb mode captures with.

I'm successfully able to set
`/actions/eosremoterelease` to `Press Full` then
`/actions/eosremoterelease` to `Release Full`
to trigger a capture, the file is then stored in memory in the camera, but I'm having trouble downloading that file to the computer.

I'm attempting to do this:

```typescript
    const cameraFilePath = new GPhoto.CameraFilePath()

    const cameraFile = await cameraFilePath.newFileAsync(this.camera.pointer)

    if (!cameraFile) {
      console.warn('cameraFile was undefined', cameraFile)
      return
    }

    const { data } = await cameraFile.getDataAndSizeAsync('binary')

    console.log('Fetched camera file')
```

But the `await cameraFile.getDataAndSizeAsync('binary')` call is erroring with this:

```
Error: reinterpret: Cannot reinterpret from NULL pointer
```

I don't understand how the `CameraFile`'s path and filename properties are being set? They're both blank. I also don't understand how cameraFile's pointer gets set?

`cameraFile.pointer` is seemingly an empty buffer
`cameraFile.buffer` is `30dd7151a47f0000` in hex

I can successfully trigger a regular capture with:

```typescript

const cameraFile = await this.camera.captureImageAsync()
const { data } = await cameraFile.getDataAndSizeAsync('binary')
```

Thanks for your help.

**Comment by Romakita** [comment]
Hello,
cameraFilePath is just a pointer/buffer to store data.
If I look on the captureAsync source code (https://github.com/TypedProject/ts-gphoto2-driver/blob/master/src/components/Camera.ts#L347), the code should be something like that:
```typescript
    const camera = new Camera() 
    const cameraFilePath = new GPhoto.CameraFilePath()
    
    await camera.captureAsync(GPCameraCaptureType.GP_CAPTURE_IMAGE, cameraFilePath.buffer, Context.get().pointer);

    const cameraFile = await cameraFilePath.newFileAsync(camera.pointer);
    if (!cameraFile) {
      console.warn('cameraFile was undefined', cameraFile)
      return
    }

    const { data } = await cameraFile.getDataAndSizeAsync('binary')
```
See you
Romain

**Comment by Mike-Dax** [comment]
So that works when capturing the image inline there, but I'm trying to separately trigger bulb mode opening and closing, then 'very asynchronously' retrieve the photo.

I guess I'm looking for something along the lines of this:

```
    await this.camera.callAsync("file_get" ... );
```

However I'm not sure what the path of the photo is when triggering bulb mode like this, or how to actually call that kind of method?
