### ISSUE TITLE
Async captures

### ISSUE THREAD

**Issue by Mike-Dax** [TypedProject/ts-gphoto2-driver#13]
Hi there,

I'm calling `camera.captureImageAsync()` and it appears to block?

Is there a trick to getting this to work asyncronously? 

I'm using a Canon 6D if that's helpful, on MacOS.

**Comment by Tronix117** [comment]
same here on a Nikon D5000

**Comment by Romakita** [comment]
I see in the code the async function aren't wrapped correctly. I hope It'll fix your problem.
If not, I haven't idea, because is totally dependent on libuv module.
install 2.3.0 and tell me.
See you

**Comment by Mike-Dax** [comment]
Unfortunately that hasn't seemed to help.

For my testing I'm running roughly this setup:

```typescript
console.log('Beginning capture loop')

let counter = 0

const int = setInterval(
  () => console.log('incrementing counter', counter++),
  100,
)

console.log('Waiting for 1 second with regular settimeout')

await new Promise((res, rej) => setTimeout(res, 1000))

console.log('Starting camera capture')
console.time('capture')

const cameraFile = await this.camera.captureImageAsync()

console.timeEnd('capture')
console.log('Finished camera capture')



console.log('Fetching camera file')
console.time('fetch')

const { data } = await cameraFile!.getDataAndSizeAsync('binary')

console.timeEnd('fetch')
console.log('Fetched camera file')


cameraFile!.close()

clearInterval(int)
```

![image](https://user-images.githubusercontent.com/13504878/64946008-15ea5300-d8b1-11e9-95ed-7c8909b4057a.png)

And while the timer will correctly increment every 100ms during the artificial `setTimeout` section, once the camera capture starts, it stops incrementing until the camera has finished the capture.

**Comment by Tronix117** [comment]
Observing the same issue :/
Actually it seems all calls are blocking the process.
