### ISSUE TITLE
Type 'typeof internal' is not a constructor function type

### ISSUE THREAD

**Issue by jmcomby** [TypedProject/ts-gphoto2-driver#14]
After importing your project with
`npm install @typedproject/gphoto2-driver`
I got this error when i compiling my project:

> node_modules/@typedproject/gphoto2-driver/lib/components/Liveview.d.ts:5:39 - error TS2507: Type 'typeof internal' is not a constructor function type.
5 export declare class Liveview extends EventEmitter implements ICloseable {

My tsconfig.json:
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs", 
    "sourceMap": true, 
    "outDir": "./build",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "resolveJsonModule": true,
    "esModuleInterop": true 
  }
}

Node version: 10.16.0

**Comment by goooseman** [comment]
@jmcomby Hi!

And what typescript version are you using? Do `npm list typescript` in the root of your project.

**Comment by jmcomby** [comment]
Typescript Version 3.5.3
Here my package.json
{
"name": "remotecanon",
"version": "1.0.0",
"description": "",
"main": "build/app.js",
"scripts": {
"tsc": "tsc",
"test": "echo \"Error: no test specified\" && exit 1"
},
"author": "",
"license": "ISC",
"dependencies": {
"@typedproject/gphoto2-driver": "^2.2.2",
"express": "^4.17.1",
"spdy": "^4.0.1",
"typescript": "^3.5.3"
},
"devDependencies": {
"@types/express": "^4.17.0",
"@types/ref": "0.0.28",
"@types/ref-struct": "0.0.29"
}
}

Actually, your project is working even with this compile error.

Le dim. 4 août 2019 à 10:35, Alexander Gusev <notifications@github.com> a
écrit :

**Comment by goooseman** [comment]
I've reproduced the issue, it happens only if `"strictNullChecks": true,`

**Comment by goooseman** [comment]
Ok, `strictNullChecks` was not an issue. The real issue was `esModuleInterop`.

The project was compiled with ts 2.9 without `esModuleInterop`. 

So if your project has following values together:

```
    "strictNullChecks": true,
    "esModuleInterop": true,
```

You will get an error.

So you have three options to fix the issue.

1. Set on of them to `false`
1. Add `"exclude": ["node_modules"]` to the root of your `tsconfig.json`
1. Fork this repo, update typescript, change `esModuleInterop` to true, fix the error and send us a PR 👍

**Comment by goooseman** [comment]
Issue was resolved in #15
