### ISSUE TITLE
Project build fails on M1 Macs

### ISSUE THREAD

**Issue by esarthou** [TypedProject/ts-gphoto2-driver#25]
Hi there,

I've noticed that running npm install on this repo on an M1 mac results in a failure:

`  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
../deps/libffi/src/prep_cif.c:26:10: fatal error: 'ffi.h' file not found
#include <ffi.h>
         ^~~~~~~
⠴ Building module: ffi-napi, Completed: 01 error generated.
make: *** [Release/obj.target/ffi/deps/libffi/src/prep_cif.o] Error 1
✖ Rebuild Failed`

This error is caused by this dependency 'ffi-napi' adn was fixed on their repo here:
https://github.com/node-ffi-napi/node-ffi-napi/issues/118
https://github.com/node-ffi-napi/node-ffi-napi/commit/e09bb91c7805fe1a0e70977e0f3270873a481e0a

I'm opening a PR to update the dependency to its latest version

EDIT: PR: https://github.com/TypedProject/ts-gphoto2-driver/pull/26

**Comment by Romakita** [comment]
Hello @esarthou 
Thanks for your feedback. I’ll merge the PR ;)

**Comment by Romakita** [comment]
released :)
