### ISSUE TITLE
getter on single prop

### ISSUE THREAD

**Issue by Nic2012** [TypedProject/ts-gphoto2-driver#9]
Hi,
following scenario:
1)
```
let cfg = new CameraWidgets(camera);
...
cfg.get('/capturesettings/shutterspeed2').value = '1/1000';
```
camera was set on M (manual mode) and shutter is now at 1/1000
2)
`cfg.get('/capturesettings/expprogram').value = 'A';`
switching to mode A (shutter will be autom. set depending on light conditions)
3) cfg.get('/capturesettings/shutterspeed2').value > still on '1/1000', but camera shows diff. value :(
4) To see actual value I have to recall new CameraWidgets(camera) again!

Each call `new CameraWidgets()` costs with 334 properties on my camera around 3 seconds :(

I see that y have changed the code that new CameraWidgets() fills a Map and every `get `returns the entry from Map not from camera directly.

Imagine there are e.g. batterylevel or lightmeter values that are always changed by camera, is there any single getter call on certain prop to the camera?

Nic

**Comment by Nic2012** [comment]
"single getter call on certain prop"=widget

**Comment by Romakita** [comment]
Ok can you give me an example code of what do you want :) ?

**Comment by Nic2012** [comment]
""single getter call on certain prop"=widget" means we are talking about the same :)
Or what do mean? I described a case in my 1st comment...

**Comment by Nic2012** [comment]
I thought widget.value = xyz persistents already in camera?
What do I have to call to get actual value from camera not from map?

**Comment by Romakita** [comment]
So I have to revert my changes. But I don't understand why the value isn't up to date because, the Map isn't a cache, it call directly the Camera to know the new value. So that mean, libphoto2 didn't give correctly the new value when a change is applied via the Camera Configuration (physically). Let find a solution...

**Comment by Romakita** [comment]
Ok I've create a new released on NPM with some optimization and fix toJSON method also.

Now you can do that:
```typescript
const cameraList = new CameraList().load();
const camera =  cameraList.getCamera(0);

// to apply a list of settings
camera.widgets.apply({
   '/path/settings': 'value',
   ....
}); 
// Apply refresh all widget's pointer after have set all values. 
// It's almost equivalent to new CameraWidget() (but optimized and transparent for you).

camera.widget.get('/path/settings').value => 'return the current Value'.

// For the battery level it preferable to trigger the refresh method before get the new value.
camera.widgets.refresh();
camera.widgets.get('/batteryvalue');
```

Also I've fixed the Widget.toJSON() method (readonly is here, and choices, range and info are cleaned).

Can you test the new release please ?
See you
Romain

**Comment by Nic2012** [comment]
Ok, I havent test this usecase with the previous version (before refactor toJSON), but I think the easiet test case would be when y endless loop e.g. on get lightmeter value, and cover partly the lens. Then the lightmeter value should given alsways different values.
In the evening I have access to the camera and can test the other fixes.

**Comment by Nic2012** [comment]
Maybe it helps, in earlier apps I used gphoto2 cl.
To verify the set value I called mostly setter and getter one after another
<gphoto2 --set-config shutterspeed2='1/1000' --get-config shutterspeed2>
The CLI isnt that top performer but the response of both cmds was fine, so I think there must be way to solve this.

**Comment by Nic2012** [comment]
Update latest version from npm

Run the following code:
```
const { CameraList, closeQuietly } = require('@typedproject/gphoto2-driver');
const cameraList = new CameraList().load();

if (cameraList.size) {
  const camera = cameraList.getCamera(0);
  camera.widgets.apply({
    '/capturesettings/expprogram': 'A',
    '/capturesettings/burstnumber': 3,
    '/imgsettings/iso': 1000
  });

  console.log('/capturesettings/expprogram', camera.widgets.get('/capturesettings/expprogram').value);
  console.log('/capturesettings/burstnumber', camera.widgets.get('/capturesettings/burstnumber').value);
  console.log('/imgsettings/iso', camera.widgets.get('/imgsettings/iso').value);

  closeQuietly(camera);
}
cameraList.close();
```
returns exceptions:
```
/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/CameraWidgets.ts:115
        this.get(key).applyValue(obj[key], false);
                      ^
TypeError: this.get(...).applyValue is not a function
    at Object.keys.forEach.key (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/CameraWidgets.ts:115:23)
    at Array.forEach (<anonymous>)
    at Map.apply (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/CameraWidgets.ts:114:24)
    at Object.<anonymous> (/home/pi/widgets.js:14:18)
    at Module._compile (module.js:632:14)

```

**Comment by Nic2012** [comment]
Changed the code a bit:
```
...
  const camera = cameraList.getCamera(0);

  camera.widgets.refresh();
  console.log('lightmeter', camera.widgets.get('/status/lightmeter').value);
...
```
returns at refresh() method
```
/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Widget.ts:18
  set pointer(pointer: PointerCameraWidget) {
             ^
RangeError: Maximum call stack size exceeded
    at Widget.set pointer [as pointer] (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Widget.ts:18:14)
    at Widget.set pointer [as pointer] (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Widget.ts:19:17)
    at Widget.set pointer [as pointer] (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Widget.ts:19:17)...
```

**Comment by Nic2012** [comment]
Is there any restrictions using the driver calls inside setTimeout/setInterval?
Because when I have e.g.
```
  console.log('lightmeter', camera.widgets.get('/status/lightmeter').value);

  let intervalHandle = setInterval( ()=>{
    console.log('lightmeter', camera.widgets.get('/status/lightmeter').value);
  }, 2000);
```
First get returns lightmeter fine, but inside the callback from the interval, it seems camera gets close and returns:
```
/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Camera.ts:93
      throw new Error("Invalid state: closed");
            ^
Error: Invalid state: closed
    at Camera.checkNotClosed (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Camera.ts:93:13)
    at Camera.get widgets [as widgets] (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Camera.ts:22:10)
    at Timeout.setInterval [as _onTimeout] (/home/pi/widgets.js:14:38)
    at ontimeout (timers.js:475:11)
```

**Comment by Nic2012** [comment]
toJSON() works fine: `console.log('lightmeter', camera.widgets.get('/status/lightmeter').toJSON());`
Returns:
lightmeter { path: '/status/lightmeter',
  label: 'Light Meter',
  type: 
   WidgetTypes {
     _cval: 3,
     _hasValue: true,
     _hasChoices: false,
     _acceptNullValue: false,
     _valueType: [Function: Number] },
  value: -20,
  changed: false,
  range: WidgetRange { min: -60, max: 60, step: 1 },
  readonly: true }

**Comment by Nic2012** [comment]
@Romakita: This project is now mentioned and referenced by http://gphoto.org/proj/

Did y recognize my comment there are at least 2 Blocker in current driver version? Maybe y forgot some files to update on npm...

**Comment by Romakita** [comment]
@Nic2012 Thanks for your effort.

Yes I saw your message. I haven't produce fix. The main problem to dev on this lib is, we need a camera XD.

I'll fix that ASAP ;)

**Comment by Romakita** [comment]
First get returns lightmeter fine, but inside the callback from the interval, it seems camera gets close and returns:

/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Camera.ts:93
      throw new Error("Invalid state: closed");
            ^
Error: Invalid state: closed
    at Camera.checkNotClosed (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Camera.ts:93:13)
    at Camera.get widgets [as widgets] (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Camera.ts:22:10)
    at Timeout.setInterval [as _onTimeout] (/home/pi/widgets.js:14:38)
    at ontimeout (timers.js:475:11)

Normal, you have closed the camera ;). Remember, in javascript setTimeout is asynchronous and all code written after setTimeout is executed just after the creation of your timer. To avoid that, comment closeQuietly() method in your code.

**Comment by Romakita** [comment]
I released a new version. I've tested this example with:

```javascript
const fs = require('fs');
const { CameraList, CameraWidgets, closeQuietly } = require('../src');
// If you launch this example not from library folder, change the previous line to:
// const { CameraList, closeQuietly } = require('@typedproject/gphoto2-driver');

const cameraList = new CameraList().load();

console.log('Nb camera', cameraList.size);

if (cameraList.size) {
  // Get current camera
  const camera = cameraList.getCamera(0);

  console.log(camera.toString());
  console.log(camera.widgets.toString());

  // change value
  camera.widgets.get('/actions/autofocusdrive').value = true;
  camera.widgets.get('/settings/autofocus').value = 'on';

  // OR apply
  camera.widgets.apply({
    '/actions/autofocusdrive': true,
    '/settings/autofocus': 'on'
  });

  console.log('/actions/autofocusdrive', camera.widgets.get('/actions/autofocusdrive').value);
  console.log('/settings/autofocus', camera.widgets.get('/settings/autofocus').value);

  const flashopen = camera.widgets.get('/status/flashopen');

  setInterval(() => {
    camera.widgets.refresh();
    console.log('/status/flashopen (1) =>', new CameraWidgets(camera).get('/status/flashopen').value);
    console.log('/status/flashopen (2) =>', flashopen.value);
  }, 1000);

  // camera.widgets => Widget which inherit from Map class
  const widgets = JSON.stringify(camera.widgets, null, 2);
  fs.writeFileSync('../.tmp/widgets.json', widgets, { encoding: 'utf8' });
}
```
For me all values are updated correctly. I found a value, I can change on physical device, the flashopen status. Can you confirm, it works for you also. The lightmeter status is always at 0% for me...

I think the support of certain settings depend on the driver from libphoto2.

See you,
Romain

**Comment by Romakita** [comment]
v2.1.1 released

**Comment by Nic2012** [comment]
> Normal, you have closed the camera ;). Remember, in javascript setTimeout is asynchronous and all code written after setTimeout is executed just after the creation of your timer.

Yeah that could be, didnt recognize that my script runs further on. I will check the code and give feedback.

Another question about calling a sequence of commands one after another: e.g.
```
1) cfg.get('/capturesettings/expprogram').value = 'A';
2) const newSpeed = cfg.get('/capturesettings/shutterspeed2').value;
3) cfg.get('/capturesettings/expprogram').value = 'M';
4) cfg.get('/capturesettings/shutterspeed2').value = newSpeed;
```
After setting 3) camera sometimes seems to be still busy and doesnt accept the 4) command.
Is there any possibility to find out if previous set of a command isnt fully finished?

**Comment by Romakita** [comment]
I don't know... the libphoto2 doesn't provide the possibility to know when a command is fully finished. 
And the problem persist, It should be better to use asynchronous API, with the possibility to catch this exception and apply the value correctly when it's possible.

**Comment by Nic2012** [comment]
Which asynchronous API do y mean? in my code?

**Comment by Nic2012** [comment]
Tested latest version 2.1.1:
Jeah, great work: set/apply on single value works fine also inside timer interval.
First fetch on full config tree cost with my Nikon D700 around 2 seconds, every next widgets.refresh() cost another 900 milliseconds.

With the following code
```
const { CameraList, CameraWidgets, closeQuietly } = require('@typedproject/gphoto2-driver');
const cameraList = new CameraList().load();
if (cameraList.size) {
  const camera = cameraList.getCamera(0);

  camera.widgets.apply({
    '/capturesettings/expprogram': 'A'
  });
  camera.widgets.refresh();
  const currentSpeed = camera.widgets.get('/capturesettings/shutterspeed2').value;

  camera.widgets.apply({
    '/capturesettings/expprogram': 'M',
    '/capturesettings/shutterspeed2': currentSpeed
  });
  console.log('shutterspeed2:', camera.widgets.get('/capturesettings/shutterspeed2').value);

  closeQuietly(camera);
}
cameraList.close();
```
returns with an exception:
```
/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Widget.ts:195
      throw new Error(`Parameter name: invalid value ${this.path} [read-only]`);
            ^
Error: Parameter name: invalid value /capturesettings/shutterspeed2 [read-only]
    at Widget.setValue (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/Widget.ts:195:13)
    at Object.keys.forEach.key (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/CameraWidgets.ts:115:23)
    at Array.forEach (<anonymous>)
    at Map.apply (/home/pi/node_modules/@typedproject/gphoto2-driver/src/components/CameraWidgets.ts:114:24)
```
Can y check if y have the same behaviour with y camera, my Nikon is a bit old stuff :)

Would it be possible to implement a bit more robust that setValue is waiting for a while as long the prop is still in read only and secured by timeout (after 1sec it returns an exception)?
